sonar.projectKey=finflow-loan-management-system
sonar.projectName=FinFlow Loan Management System
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8
sonar.java.source=17

sonar.sources=auth-service/src/main/java,application-service/application-service/src/main/java,document-service/document-service/src/main/java,admin-service/admin-service/src/main/java,api-gateway/src/main/java,eureka-serverr/eureka-server/src/main/java
sonar.tests=auth-service/src/test/java,application-service/application-service/src/test/java,document-service/document-service/src/test/java,admin-service/admin-service/src/test/java,api-gateway/src/test/java,eureka-serverr/eureka-server/src/test/java

sonar.java.binaries=auth-service/target/classes,application-service/application-service/target/classes,document-service/document-service/target/classes,admin-service/admin-service/target/classes,api-gateway/target/classes,eureka-serverr/eureka-server/target/classes
sonar.java.test.binaries=auth-service/target/test-classes,application-service/application-service/target/test-classes,document-service/document-service/target/test-classes,admin-service/admin-service/target/test-classes,api-gateway/target/test-classes,eureka-serverr/eureka-server/target/test-classes

sonar.junit.reportPaths=auth-service/target/surefire-reports,application-service/application-service/target/surefire-reports,document-service/document-service/target/surefire-reports,admin-service/admin-service/target/surefire-reports,api-gateway/target/surefire-reports,eureka-serverr/eureka-server/target/surefire-reports

sonar.exclusions=**/target/**,**/.idea/**,**/*.iml,**/mvnw,**/mvnw.cmd
sonar.coverage.exclusions=**/*Application.java,**/*Config.java,**/*OpenApiConfig.java,**/*Dto.java,**/dto/**,**/entity/**,**/repository/**
